apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
data:
  runtime.slice: |
    [Unit]
    Description=Limited resources slice for Kubernetes services
    Documentation=man:systemd.special(7)
    DefaultDependencies=no
    Before=slices.target
    Requires=-.slice
    After=-.slice
  10-cgroup.conf: |
    [Service]
    CPUAccounting=true
    MemoryAccounting=true
    Slice=runtime.slice
