apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
data:
  daemon.json: |
    {
      "live-restore": true,
      "log-driver": "json-file",
      "log-opts":  {
         "max-size": "50m",
         "max-file": "5"
      }
    }
